### ISSUE TITLE
Building database error with test data

### ISSUE THREAD

**Issue by sandyplus** [pauline-ng/SIFT4G_Create_Genomic_DB#16]
Dear Pauline,
I cannot get prediction files for my data. To trace the error, I used the test data of Homo sapiens to build a database. I deleted the dbSNP and mitochondrial data because my data have no such data. I tested the command to build the database:
```bash
 perl make-SIFT-db-all.pl -config test_files/homo_sapiens_test.config
```
Although it produced the prediction files, the error shows like this:
```bash
Use of uninitialized value $fasta_subseq in concatenation (.) or string at make-single-records-BIOPERL.pl
Use of uninitialized value $fasta_subseq in concatenation (.) or string at generate-fasta-subst-files-BIOPERL.pl line 446, <IN_TX> line 1435.
Use of uninitialized value $fasta_subseq in concatenation (.) or string at generate-fasta-subst-files-BIOPERL.pl line 446, <IN_TX> line 1461.
done making the fasta sequences
start siftsharp, getting the alignments
/home/shiyong/software/SIFT4G/sift4g/bin/sift4g -d /home/shiyong/database/NCBI/UNIREF90/uniref90.fasta -q ./test_files/homo_sapiens_test/all_prot.fasta --subst ./test_files/homo_sapiens_test/subst --out ./test_files/homo_sapiens_test/SIFT_predictions --sub-results
** Checking query data and substitutions files **
* processing queries: 100.00/100.00% *

** Searching database for candidate sequences **
* processing database part 194 (size ~0.25 GB): 100.00/100.00% *

** Aligning queries with candidate sequences **
* processing database part 49 (size ~1.00 GB): 100.00/100.00% *

** Selecting alignments with median threshold: 2.75 **
* processing queries: 100.00/100.00% *

** Generating SIFT predictions with sequence identity: 100.00% **
* processing queries: 100.00/100.00% *

done getting all the scores
populating databases
Traceback (most recent call last):
  File "make_regions_file.py", line 68, in <module>
    get_regions (chrom_file, out_file)
  File "make_regions_file.py", line 31, in get_regions
    pos = get_pos (first_line)
  File "make_regions_file.py", line 8, in get_pos
    return int (fields[0])
ValueError: invalid literal for int() with base 10: ''
checking the databases
zipping up ./test_files/homo_sapiens_test/chr-src/*
All done!
```
FIY, the config file (homo_sapiens_test.config) looks like this:
```bash
GENETIC_CODE_TABLE=1
GENETIC_CODE_TABLENAME=Standard
MITO_GENETIC_CODE_TABLE=2
MITO_GENETIC_CODE_TABLENAME=Vertebrate Mitochondrial

PARENT_DIR=./test_files/homo_sapiens_test
ORG=homo_sapiens
ORG_VERSION=GRCh38.83
DBSNP_VCF_FILE=

#Running SIFT 4G
SIFT4G_PATH=/home/shiyong/software/SIFT4G/sift4g/bin/sift4g
PROTEIN_DB=/home/shiyong/database/NCBI/UNIREF90/uniref90.fasta

# Sub-directories, don't need to change
GENE_DOWNLOAD_DEST=gene-annotation-src
CHR_DOWNLOAD_DEST=chr-src
LOGFILE=Log.txt
ZLOGFILE=Log2.txt
FASTA_DIR=fasta
SUBST_DIR=subst
ALIGN_DIR=SIFT_alignments
SIFT_SCORE_DIR=SIFT_predictions
SINGLE_REC_BY_CHR_DIR=singleRecords
SINGLE_REC_WITH_SIFTSCORE_DIR=singleRecords_with_scores
DBSNP_DIR=dbSNP

# Doesn't need to change
FASTA_LOG=fasta.log
INVALID_LOG=invalid.log
PEPTIDE_LOG=peptide.log
ENS_PATTERN=ENS
SINGLE_RECORD_PATTERN=:change:_aa1valid_dbsnp.singleRecord

```
I would be appreciated if you provide any suggestions.
My old post is [here](https://github.com/rvaser/sift4g/issues/5).
If you need more information, please feel free to contact me.

Best regards,
Sandy

**Comment by pauline-ng** [comment]
If you type:

ls GRCh38.83/

what do you see?

Thanks,
Pauline

**Comment by sandyplus** [comment]
Hi, Pauline,
The `ls GRCh38.83` shows:
```bash
1.gz  21.regions  21_SIFTDB_stats.txt  CHECK_GENES.LOG  homo_sapiens_test.config  MT.gz  MT.regions  MT_SIFTDB_stats.txt
```

Best regards,
Sandy

**Comment by pauline-ng** [comment]
I type

`ls -lt`

and see

`-rw-r--r-- 1 pauline pauline    230183 Dec  4 15:43 MT.gz

-rw-r--r-- 1 pauline pauline       444 Dec  4 15:43 MT.regions

-rw-r--r-- 1 pauline pauline 230778585 Dec  4 15:43 21.gz

-rw-r--r-- 1 pauline pauline    117688 Dec  4 15:42 21.regions
`

Are the sizes of your files comparable to mine?  If yes, you've built the databases

**Comment by sandyplus** [comment]
Dear Pauline,
I deleted the mitochondrial data. So the MT.regions is empty.
My result shows:
```
-rw-r--r-- 1 shiyong WangBS       880 Dec 16 16:53 homo_sapiens_test.config
-rw-r--r-- 1 shiyong WangBS       142 Dec 16 16:53 MT_SIFTDB_stats.txt
-rw-r--r-- 1 shiyong WangBS       442 Dec 16 16:53 21_SIFTDB_stats.txt
-rw-r--r-- 1 shiyong WangBS       218 Dec 16 16:49 CHECK_GENES.LOG
-rw-r--r-- 1 shiyong WangBS       184 Dec 16 16:46 MT.gz
-rw-r--r-- 1 shiyong WangBS         0 Dec 16 16:46 MT.regions
-rw-r--r-- 1 shiyong WangBS 231379540 Dec 16 16:46 21.gz
-rw-r--r-- 1 shiyong WangBS    117688 Dec 16 16:43 21.regions
```
It seems that the database built up successfully with test data, although some python error still shows up.
However, I still cannot build the database with my own data if I do not remove DNA fasta sequences with "NNN".  More information is posted [here](https://github.com/rvaser/sift4g/issues/5).

I cannot remove these sequences because most of them contain "NNN". Any suggestions?

Best regards,
Sandy

**Comment by pauline-ng** [comment]
Sandy -- I am the same person looking into the other issue. Please be patient.

Issue #16: Test database was built successfully. Closed issue.
