### ISSUE TITLE
Errors in building my own database for rheMac10

### ISSUE THREAD

**Issue by npb596** [pauline-ng/SIFT4G_Create_Genomic_DB#70]
Hello,

I have had errors in attempting to create a database for rheMac10 (or MMul_10). There already is a database for rheMac8 (MMul_8) for some reference. I have my own FASTA reference and gtf file and have successfully created a test database for the homo-sapiens_test provided as an examples in test_files. I've allowed the program to run in excess of 24 hours so I think I've gotten the maximal output possible so far.

I'll try my best to describe the errors and give my output and config. The latter should differ only from homo_sapiens-test.txt in the following lines:

PARENT_DIR=/home/npb0015/reinforcement_project/
ORG=macaca_mulatta
ORG_VERSION=Mmul_10.99

#Running SIFT 4G
SIFT4G_PATH=/tools/sift4g-1/bin/sift4g
PROTEIN_DB=/home/npb0015/reinforcement_project/Reference_files/uniprot_sprot.fasta

# Sub-directories, don't need to change
GENE_DOWNLOAD_DEST=Reference_files/
CHR_DOWNLOAD_DEST=Reference_files/

The error messages I receive are the following two lines repeated several times:

Use of uninitialized value $aa in string eq at make-single-records-BIOPERL.pl line 274.
Use of uninitialized value $aa in concatenation (.) or string at make-single-records-BIOPERL.pl line 280.

Then the following repeated several times:

Use of uninitialized value $orig_aa in string eq at make-single-records-BIOPERL.pl line 551.
Use of uninitialized value $mutated_aa in string eq at make-single-records-BIOPERL.pl line 551.

Then the following repeated several times:

Use of uninitialized value in concatenation (.) or string at make-single-records-BIOPERL.pl line 305.

And are are at least a hundred thousand blocks like that. Then later on blocks of the following repeated:

Use of uninitialized value $mutated_aa in string eq at generate-fasta-subst-files-BIOPERL.pl line 894
Use of uninitialized value $aa2 in string eq at generate-fasta-subst-files-BIOPERL.pl line 621.
Use of uninitialized value $aa2 in string ne at generate-fasta-subst-files-BIOPERL.pl line 626.

When the program is done it seems to populate singleRecords, subst, and fasta folders with a substantive number of files looking correct. The main folder is populated with log files and the Reference_files directory does have txt files. All other directories in the config file and particularly the Mmul_10.99 is never populated. When I annotated a VCF using the directory it seems as though there's no SIFT annotations occuring.

I hope this has been sufficiently detailed and would greatly appreciate help.

**Comment by pauline-ng** [comment]
You can ignore the unitialized value messages.

Can you list the folders / files in your sift4g directory ? If there's > 10 files in a folder, just list the first few so I know that there are some files present.

**Comment by npb596** [comment]
When you say the sift4g directory I'm assuming you mean the one where I'm calling the sift4g command from? I'm using an HPC that sift4g was loaded to where I can see this directory: 

/tools/sift4g-1/ 

has the folllowing content:

bin  LICENSE  Makefile  README.md  sift4g  test_files  vendor

and inside the sift4g directory above:

LICENSE  Makefile  obj  src

**Comment by pauline-ng** [comment]
Hi Nick,  

I mean list the files that are being generated in the **PARENT_DIR** set in your config file.

Something like what this user did (scroll down to later messages, where the user lists files & file sizes) https://github.com/pauline-ng/SIFT4G_Create_Genomic_DB/issues/69

**Comment by npb596** [comment]
Ok, thank you for the clarification. I'm listing sizes and file names here. I've put a forward slash at the end for directories (anything with 512 is not populated with files).

30M all_prot.fasta
76 fasta.log
277K invalid.log
30M peptide.log
5.8M subst/
4.0M fasta/
0 Log2.txt
128K singleRecords/
8.0K scripts/
512 SIFT_alignments/
512 SIFT_predictions/
512 singleRecords_with_scores/
512 dbSNP/
512 Mmul_10.99/

**Comment by pauline-ng** [comment]
The protein sequences and their substitutions are being generated, but sift4g (actually getting the predictions) isn't being run. This is odd if you are able to run the example files through; then sift4g should run.

What was the last error message on the screen? (Not the unitialized value messages, but the last message). Maybe it ran out of memory?

What happens if you try running sift4g directly:
`/tools/sift4g-1/bin/sift4g -d /home/npb0015/reinforcement_project/Reference_files/uniprot_sprot.fasta -q all_prot.fasta --subst /home/npb0015/reinforcement_project/subst --out /home/npb0015/reinforcement_project/SIFT_predictions/ --sub-results`

**Comment by npb596** [comment]
The last messages were:

start siftsharp, getting the alignments
/tools/sift4g-1/bin/sift4g -d /home/npb0015/reinforcement_project/Reference_files/uniprot_sprot.fasta -q /home/npb0015/reinforcement_project/
** Checking query data and substitutions files **
* processing queries: 0.00/100.00% *^M* processing queries: 0.00/100.00% *^M* processing queries: 0.01/100.00% *^M* processing queries: 0.01/

** Searching database for candidate sequences **
* processing database part 1 (size ~0.25 GB): 0.00/100.00% *^M* processing database part 1 (size ~0.25 GB): 2.50/100.00% *^M* processing data

Which makes me think maybe it was running but simply didn't have the time needed to finish... though I gave it 46 hours and 100GB RAM.

Running the command you sent seems to start the process that is being detailed in those messages. Would it be worthwhile to simply run a job using just that command (I'm on an HPC and not wanting to use the login node if that process will take too long)?

**Comment by pauline-ng** [comment]
Yes, just run the job using that command. After sift4g has completed running,  run the script below. This script skips the preceding steps and picks up where it assumes sift4g has finished running.

[make-SIFT-db-all-downstream-sift4g.txt](https://github.com/pauline-ng/SIFT4G_Create_Genomic_DB/files/9807646/make-SIFT-db-all-downstream-sift4g.txt)

Github doesn't let me upload .pl files, so 

1) Rename the file above to `make-SIFT-db-all-downstream-sift4g.pl`

2) Run script:
`perl make-SIFT-db-all-downstream-sift4g.pl -conf <config file>`

**Comment by pauline-ng** [comment]
Install python3  so that the command ` python -v `  shows python3

Rerun 'perl make-SIFT-db-all-downstream-sift4g.pl -config rheMac10.config.txt'

The *.regions file is generated by a python script and needs to be present.

Don't worry about the chr prefix

**Comment by npb596** [comment]
I think python3 is loaded to the HPC by default but to be certain I did load python/3.9.2 into the script and reran. I am receiving the same errors though there are regions files in Mmul_10.99. Mmul_10.99 is produced in reinforcement_project not reinforcement_project/Reference_files as per the config file so is that an issue? I can't guess what else would be right now.

**Comment by pauline-ng** [comment]
You type`python` and it runs python3 and not python2? You did run the test file and it worked right? (the test examples created regions files?)

I don't quite understand your last 2 sentences -- they are unclear and muddled.

**Comment by pauline-ng** [comment]
According to your first message, your parent directory is : 

PARENT_DIR=/home/npb0015/reinforcement_project/

and that's where files are being generated, which is correct.

**Comment by pauline-ng** [comment]
Please list the files in your `singleRecords_with_scores` directory

**Comment by npb596** [comment]
Apologies for the lack of clarity in my last message. If the files should be in /home/npb0015/reinforcement_project/ then I was just muddling up the issue.

The test example I used did create the relevant regions files and did populate it's own singleRecords_with_scores directory. The singleRecords_with_scores directory for my current attempts with MMul_10.99 is empty. I am definitely running python3, not python2, confirmed with running "python -v".

**Comment by pauline-ng** [comment]
"The singleRecords_with_scores directory for my current attempts with MMul_10.99 is empty."

This makes me think you don't have SIFT predictions. Can you list directories and their file sizes like you did ~6 days ago?

**Comment by npb596** [comment]
30M all_prot.fasta
76 fasta.log
277K invalid.log
30M peptide.log
5.8M subst/
4.0M fasta/
0 Log2.txt
128K singleRecords/
512 SIFT_alignments/
512 SIFT_predictions/
128K singleRecords_with_scores/
512 dbSNP/
128K Mmul_10.99/

As before, directories with 512 are empty so that suggests the SIFT_predictions directory is still empty. The only two changes in directory size I can see from 6 days ago is that Mmul_10.99 has increased in size (as it is now populated when it wasn't 6 days ago) and singleRecords_with_scores is showing that it's 128K (instead of 512B as before) but it is clear it is actually empty, even searching for hidden files. To be more transparent, reinforcement_project (the directory containing all of the above) does have other directories (e.g. one containing my VCFs) but I assumed it's only worth noting ones being generated by the perl scripts.

**Comment by pauline-ng** [comment]
Your sift4g isn't finishing if there isn't anything in SIFT_predictions or SIFT_alignments.

**Comment by pauline-ng** [comment]
Closed due to lack of activity.

**Comment by npb596** [comment]
I apologize for the lack of activity, I had issues in my personal life that delayed my work on this for a bit and I realized at some point there was an issue specific to the HPCC I was using, so I was in contact with the HPC admin at my university for a while to troubleshoot that. The issue there specifically is that in the slurm-373314.txt file I posted almost a month ago there was an "Illegal Instruction" error that suggested sift4g was not properly compiled on the amd node I was using. This did not affect my runs with the test_files because I ran those on a login node, which was Intel. The HPC staff graciously recompiled the program on the amd node, so the Illegal Instruction error has been replaced by a segmentation fault error. This is the most recent output I get:

** Aligning queries with candidate sequences **
* processing database part 1 (size ~1.00 GB): 0.00/100.00% *
* processing database part 1 (size ~1.00 GB): 2.50/100.00% *
* processing database part 1 (size ~1.00 GB): 5.00/100.00% *
* processing database part 1 (size ~1.00 GB): 7.50/100.00% *
* processing database part 1 (size ~1.00 GB): 10.00/100.00% *
* processing database part 1 (size ~1.00 GB): 12.50/100.00% *
/cm/local/apps/slurm/var/spool/job391367/slurm_script: line 16: 18084 Segmentation fault      sift4g -t 20 -q /home/npb0015/reinforcement_project/all_prot.fasta -d /home/npb0015/reinforcement_project/Reference_files/uniprot_sprot.fasta --subst /home/npb0015/reinforcement_project/subst --out /home/npb0015/reinforcement_project/SIFT_predictions/ --sub-results

This error comes from running the sift4g command given in the error, which is essentially the same as you suggested on October 16th (I get the same error running that command exactly as is). Since a segmentation fault usually means an inability to access the memory required I've tried runs as high as 248GB RAM but still receive the same error, so I assume that is not the issue.

I know this has been a long running issue but I am making progress so I greatly appreciate the help you've provided so far.

**Comment by pauline-ng** [comment]
Hi Nick,

The issue is the SIFT4G algorithm, which was written by Robert Vaser, a former student in my lab and has a separate github repo.  Can you open this issue at this repo: https://github.com/rvaser/sift4g/issues   copying  the error from the post above?

Also, if you can upload your all_prot.fasta file into dropbox, I can take a look to see if it "looks right"

**Comment by pauline-ng** [comment]
User removed proteins with X's.

Then got the following error (copied from [here](https://github.com/rvaser/sift4g/issues/30#issuecomment-1322825469)):

I removed those proteins, ran sift4g with the resulting FASTA file and there are SIFT prediction files now, thank you. When running the next step:

perl make-SIFT-db-all-downstream-sift4g.pl -config rheMac10.config.txt

I receive the following errors:

Unable to read from /home/npb0015/reinforcement_project/singleRecords/chr11_NW_021160268v1_random.singleRecords_noncoding
Traceback (most recent call last):
File "/mmfs1/home/npb0015/reinforcement_project/SIFT/scripts_to_build_SIFT_db/make_regions_file.py", line 68, in
get_regions (chrom_file, out_file)
File "/mmfs1/home/npb0015/reinforcement_project/SIFT/scripts_to_build_SIFT_db/make_regions_file.py", line 31, in get_regions
pos = get_pos (first_line)
File "/mmfs1/home/npb0015/reinforcement_project/SIFT/scripts_to_build_SIFT_db/make_regions_file.py", line 8, in get_pos
return int (fields[0])
ValueError: invalid literal for int() with base 10: ''
Unable to read from /home/npb0015/reinforcement_project/singleRecords/chr13_NW_021160278v1_random.singleRecords_noncoding
Unable to read from /home/npb0015/reinforcement_project/singleRecords/chr13_NW_021160282v1_random.singleRecords_noncoding
Unable to read from /home/npb0015/reinforcement_project/singleRecords/chr18_NW_021160356v1_random.singleRecords_noncoding
Unable to read from /home/npb0015/reinforcement_project/singleRecords/chr19_NW_021160375v1_random.singleRecords_noncoding
Unable to read from /home/npb0015/reinforcement_project/singleRecords/chr4_NW_021160155v1_random.singleRecords_noncoding
Unable to read from /home/npb0015/reinforcement_project/singleRecords/chr6_NW_021160190v1_random.singleRecords_noncoding
Unable to read from /home/npb0015/reinforcement_project/singleRecords/chr8_NW_021160222v1_random.singleRecords_noncoding
Unable to read from /home/npb0015/reinforcement_project/singleRecords/chrUn_NW_021160452v1.singleRecords_noncoding
Unable to read from /home/npb0015/reinforcement_project/singleRecords/chrUn_NW_021160484v1.singleRecords_noncoding
Unable to read from /home/npb0015/reinforcement_project/singleRecords/chrUn_NW_021161041v1.singleRecords_noncoding
Unable to read from /home/npb0015/reinforcement_project/singleRecords/chrUn_NW_021161561v1.singleRecords_noncoding
Unable to read from /home/npb0015/reinforcement_project/singleRecords/chrUn_NW_021161848v1.singleRecords_noncoding
Traceback (most recent call last):
File "/mmfs1/home/npb0015/reinforcement_project/SIFT/scripts_to_build_SIFT_db/make_regions_file.py", line 68, in
get_regions (chrom_file, out_file)
File "/mmfs1/home/npb0015/reinforcement_project/SIFT/scripts_to_build_SIFT_db/make_regions_file.py", line 31, in get_regions
pos = get_pos (first_line)
File "/mmfs1/home/npb0015/reinforcement_project/SIFT/scripts_to_build_SIFT_db/make_regions_file.py", line 8, in get_pos
return int (fields[0])
ValueError: invalid literal for int() with base 10: ''
Unable to read from /home/npb0015/reinforcement_project/singleRecords/chrUn_NW_021161853v1.singleRecords_noncoding
Unable to read from /home/npb0015/reinforcement_project/singleRecords/chrUn_NW_021161876v1.singleRecords_noncoding
Unable to read from /home/npb0015/reinforcement_project/singleRecords/chrUn_NW_021162246v1.singleRecords_noncoding
Unable to read from /home/npb0015/reinforcement_project/singleRecords/chrUn_NW_021162265v1.singleRecords_noncoding
checking the databases
zipping up /home/npb0015/reinforcement_project/Reference_files/*
gzip: /home/npb0015/reinforcement_project/Reference_files/directory.index.gz already has .gz suffix -- unchanged
gzip: /home/npb0015/reinforcement_project/Reference_files/noncoding.txt.gz already has .gz suffix -- unchanged
gzip: /home/npb0015/reinforcement_project/Reference_files/protein_coding_genes.txt.gz already has .gz suffix -- unchanged
gzip: /home/npb0015/reinforcement_project/Reference_files/rheMac10.ensGene.gtf.gz already has .gz suffix -- unchanged
All done!

These appear to be the same errors that I posted here https://github.com/pauline-ng/SIFT4G_Create_Genomic_DB/issues/70 on October 20th, when I still wasn't generating SIFT predictions properly, so not sure why the errors still appear. I am running it with python version 3.9.2. I've looked at the python script a bit and I have some suspicion the ValueError results from a missing or empty chr.gz file but I can't figure what chr would be missing as I know there are chr.gz and regions files.

**Comment by pauline-ng** [comment]
@npb596 

Can you list files & their sizes in:
 SINGLE_REC_BY_CHR_DIR
 SINGLE_REC_BY_CHR_DIR
 
 Your gff file,  is it all coding? Did it include UTRs?

Thanks,
Pauline

**Comment by npb596** [comment]
The SINGLE_REC_WITH_SIFTSCORE_DIR is empty. If I recall properly it does populate while running the database script but is empty once finished.

The SINGLE_REC_BY_CHR_DIR directory has 1628 files in it. I will post some representative ones for chr10 (though there are similar files for all chromosomes/scaffolds in the annotation as far as I can tell)

2.9G chr10.singleRecords
1.7G chr10.singleRecords_noncoding
1.4G chr10.singleRecords_noncoding.with_dbSNPid
1.6M chr10.singleRecords_proteins.fa
4.5M chr10.invalidRecords

The gtf file should include just coding transcripts (e.g. no repeat elements or anything) and it does include UTRs as part of that.

**Comment by pauline-ng** [comment]
@npb596 Please comment out line 74 of [make-SIFT-db-all-downstream-sift4g.pl](https://github.com/pauline-ng/SIFT4G_Create_Genomic_DB/blob/master/make-SIFT-db-all-downstream-sift4g.pl)

Old: `system ("rm $rm_dir");`
New: `# system ("rm $rm_dir");`

and re-run make-SIFT-db-all-downstream-sift4g.pl 

The change will stop the clean up SINGLE_REC_WITH_SIFTSCORE_DIR, and help me debug.

Then send me list & file sizes in SINGLE_REC_WITH_SIFTSCORE_DIR,

**Comment by npb596** [comment]
I have done that and now have 987 files in the SINGLE_REC_WITH_SIFTSCORE_DIR. Using chr10 as a representative example again:

0 singleRecords_with_scores/chr10_scores.Srecords.with_dbSNPid.ERR
0 singleRecords_with_scores/chr10_scores.Srecords.with_dbSNPid.LOG
2.9G singleRecords_with_scores/chr10_scores.Srecords.with_dbSNPid.sorted

It seems this pattern follows for all chromosomes/scaffolds. That is, all ERR and LOG files are empty but all the .sorted files have non-zero sizes.

**Comment by pauline-ng** [comment]
Great, thanks for rerunning it.

Now please run 
`python make_regions_file.py  singleRecords_with_scores/chr10_scores.Srecords.with_dbSNPid.sorted  tmp.regions`

Do you get any errors?
Do you see anything in tmp.regions?

**Comment by npb596** [comment]
Running that produces the following messages, which don't appear to be errors:

check_SIFTDB.py <sorted file> <outfile>
looking at chr10_scores.Srecords.with_dbSNPid.sorted

and the tmp.regions file is populated with lines like so:

1             699502  OUT
699503  701521  IN
701522  703026  OUT
703027  703263  IN
703264  703285  OUT
703286  704176  IN

alternating OUT and IN until the end of the chromosome.

**Comment by pauline-ng** [comment]
That's the right output. So I'm stumped.

Please check:

1. These are non-empty files with read access:
singleRecords_with_scores/chr*_scores.Srecords.with_dbSNPid.sorted

(this is input into make-region_files.py)

2. A folder exists with write-access (this is where the regions file will be written to)
$PARENT_DIR/$ORG_VERSION

**Comment by npb596** [comment]
Both of those conditions are fulfilled. I may restart the database build from the very beginning just in case there's any changes I made in between the beginning steps to the sift4g step, to the downstream steps, that could affect anything. I can get back to you on how that pans out.

**Comment by pauline-ng** [comment]
OK, but you'll still have to filter out the fasta sequences with "X" in them.

Can you run:
`perl make-sift-scores-db-batch.pl $metafile`

this calls the make_regions_file.py script

**Comment by npb596** [comment]
I'm assuming there needs to be an actual file in place of $metafile? I don't know which file that is. Assuming I run it exactly that way I get usage statements:

Usage: perl make-sift-scores-db-batch.pl <metafile>
Example: perl make-sift-scores-db-batch.pl mouse.txt

**Comment by pauline-ng** [comment]
Pass in your config file.

`perl make-sift-scores-db-batch.pl <config>`

**Comment by npb596** [comment]
I am posting the output file from doing that here.
[401290-Mmul10db_ds.txt](https://github.com/pauline-ng/SIFT4G_Create_Genomic_DB/files/10149624/401290-Mmul10db_ds.txt)

**Comment by pauline-ng** [comment]
It's showing no errors. All your regions files should be in:

`/home/npb0015/reinforcement_project/Mmul_10.99/`

**Comment by pauline-ng** [comment]
Try a full path for the database

java -jar SIFT4G_Annotator.jar -c -i Reinforcement.chr19.MAF.ID.vcf -d` <full path>` -r .

**Comment by npb596** [comment]
Running the following `java -jar SIFT4G_Annotator.jar -c -i Reinforcement.chr19.MAF.ID.vcf -d /home/npb0015/reinforcement_project/Mmul_10.99/ -r .`

results in a similar error, even with the copied 19.regions file:

Start Time for SIFT4G code: Tue Dec 06 10:01:37 CST 2022

Started Running .......
Running in Single transcripts mode

Chromosome	WithSIFT4GAnnotations	WithoutSIFT4GAnnotations	Progress
The following chromosomes (or scaffolds/contigs) are not found in the SIFT 4G database and will not be annotated:
19
Please contact us if you have any questions.
/home/npb0015/reinforcement_project/Mmul_10.99/19.regions does not exist
19			0			522186			Completed : 1/1

Merging temp files....
SIFT4G Annotation completed !
Output directory:.
End Time for parallel code: Tue Dec 06 10:01:48 CST 2022

**Comment by pauline-ng** [comment]
Upload the chr19 files on Dropbox and a VCF file and I can take a look.
